import type { Language } from "./demo-data";

export const copy = {
  en: {
    appName: "Offspace Digital Community",
    intro: "Schedule and attendance",
    homeTitle: "Offspace schedule access",
    homeText: "Open your schedule and attendance workspace.",
    openStudentLogin: "Student login",
    mentorLoginLink: "Mentor login",
    studentLoginTitle: "Student access",
    studentLoginText: "Enter your email and password to open the demo student schedule.",
    mentorLoginTitle: "Mentor account",
    mentorLoginText: "Use the mentor account provided by Offspace to open assigned groups.",
    studentEmail: "Student email",
    mentorEmail: "Mentor email",
    password: "Password",
    continue: "Continue",
    backHome: "Back home",
    studentDashboard: "Student dashboard",
    mentorDashboard: "Mentor dashboard",
    student: "Student",
    mentor: "Mentor",
    mentorSubtitle: "Assigned groups and private students",
    studentSubtitle: "Your current courses",
    groups: "Groups",
    privateStudents: "Private Students",
    schedule: "Schedule",
    attendance: "Attendance",
    upcoming: "Upcoming",
    completed: "Completed",
    cancelled: "Cancelled",
    present: "Present",
    absent: "Absent",
    late: "Late",
    excused: "Excused",
    notMarked: "Not marked",
    course: "Course",
    studentName: "Student",
    privateLabel: "Private",
    groupLabel: "Group",
    demoNotice: "Demo data only. Firebase is not connected to this UI yet.",
  },
  ka: {
    appName: "Offspace Digital Community",
    intro: "ცხრილი და დასწრება",
    homeTitle: "Offspace ცხრილზე წვდომა",
    homeText: "გახსენი შენი ცხრილის და დასწრების სივრცე.",
    openStudentLogin: "სტუდენტის შესვლა",
    mentorLoginLink: "მენტორის შესვლა",
    studentLoginTitle: "სტუდენტის წვდომა",
    studentLoginText: "შეიყვანე ელფოსტა და პაროლი დემო სტუდენტის ცხრილის გასახსნელად.",
    mentorLoginTitle: "მენტორის ანგარიში",
    mentorLoginText: "გამოიყენე Offspace-ის მიერ მოცემული მენტორის ანგარიში.",
    studentEmail: "სტუდენტის ელფოსტა",
    mentorEmail: "მენტორის ელფოსტა",
    password: "პაროლი",
    continue: "გაგრძელება",
    backHome: "მთავარზე დაბრუნება",
    studentDashboard: "სტუდენტის სივრცე",
    mentorDashboard: "მენტორის სივრცე",
    student: "სტუდენტი",
    mentor: "მენტორი",
    mentorSubtitle: "მიმაგრებული ჯგუფები და ინდივიდუალური სტუდენტები",
    studentSubtitle: "შენი მიმდინარე კურსები",
    groups: "ჯგუფები",
    privateStudents: "ინდივიდუალური სტუდენტები",
    schedule: "ცხრილი",
    attendance: "დასწრება",
    upcoming: "მომავალი",
    completed: "დასრულებული",
    cancelled: "გაუქმებული",
    present: "ესწრებოდა",
    absent: "არ ესწრებოდა",
    late: "დააგვიანა",
    excused: "საპატიო",
    notMarked: "არ არის მონიშნული",
    course: "კურსი",
    studentName: "სტუდენტი",
    privateLabel: "ინდივიდუალური",
    groupLabel: "ჯგუფი",
    demoNotice: "ეს მხოლოდ დემო მონაცემებია. Firebase ჯერ არ არის ჩართული UI-ში.",
  },
  ru: {
    appName: "Offspace Digital Community",
    intro: "Расписание и посещаемость",
    homeTitle: "Доступ к расписанию Offspace",
    homeText: "Откройте рабочую область расписания и посещаемости.",
    openStudentLogin: "Вход студента",
    mentorLoginLink: "Вход ментора",
    studentLoginTitle: "Доступ студента",
    studentLoginText: "Введите email и пароль, чтобы открыть демо-расписание студента.",
    mentorLoginTitle: "Аккаунт ментора",
    mentorLoginText: "Используйте аккаунт ментора, выданный Offspace.",
    studentEmail: "Email студента",
    mentorEmail: "Email ментора",
    password: "Пароль",
    continue: "Продолжить",
    backHome: "На главную",
    studentDashboard: "Кабинет студента",
    mentorDashboard: "Кабинет ментора",
    student: "Студент",
    mentor: "Ментор",
    mentorSubtitle: "Назначенные группы и индивидуальные студенты",
    studentSubtitle: "Ваши текущие курсы",
    groups: "Группы",
    privateStudents: "Индивидуальные студенты",
    schedule: "Расписание",
    attendance: "Посещаемость",
    upcoming: "Предстоит",
    completed: "Завершено",
    cancelled: "Отменено",
    present: "Был",
    absent: "Отсутствовал",
    late: "Опоздал",
    excused: "Уважительная",
    notMarked: "Не отмечено",
    course: "Курс",
    studentName: "Студент",
    privateLabel: "Индивидуально",
    groupLabel: "Группа",
    demoNotice: "Это только демо-данные. Firebase пока не подключен к UI.",
  },
} satisfies Record<Language, Record<string, string>>;
